INSERT INTO `theme-park-db`.`employees`(customer_id,title,type,message,status) VALUES ('CUST011','Don''t Forget','PROMO','Visit us this upcoming holiday','SENT');
INSERT INTO `theme-park-db`.`employees`(customer_id,title,type,message,status) VALUES ('CUST012','Don''t Forget','REMINDER','Your Visit is Comming soon','READ');
INSERT INTO `theme-park-db`.`employees`(customer_id,title,type,message,status) VALUES ('CUST069','Important Message','PROMO','Visit us this upcoming holiday','READ');
INSERT INTO `theme-park-db`.`employees`(customer_id,title,type,message,status) VALUES ('CUST085','Important Message','PROMO','Visit us this upcoming holiday','DISMISSED');
INSERT INTO `theme-park-db`.`employees`(customer_id,title,type,message,status) VALUES ('CUST034','Important Message','REMINDER','Your Visit is Comming soon','DISMISSED');
INSERT INTO `theme-park-db`.`employees`(customer_id,title,type,message,status) VALUES ('CUST091','Just a Reminder','REMINDER','Your Visit is Comming soon','READ');
INSERT INTO `theme-park-db`.`employees`(customer_id,title,type,message,status) VALUES ('CUST048','Don''t Forget','PROMO','Visit us this upcoming holiday','DISMISSED');
INSERT INTO `theme-park-db`.`employees`(customer_id,title,type,message,status) VALUES ('CUST012','Important Message','PROMO','Visit us this upcoming holiday','DISMISSED');
INSERT INTO `theme-park-db`.`employees`(customer_id,title,type,message,status) VALUES ('CUST067','Don''t Forget','REMINDER','Your Visit is Comming soon','SENT');
INSERT INTO `theme-park-db`.`employees`(customer_id,title,type,message,status) VALUES ('CUST069','Just a Reminder','PROMO','Visit us this upcoming holiday','READ');
INSERT INTO `theme-park-db`.`employees`(customer_id,title,type,message,status) VALUES ('CUST037','Don''t Forget','REMINDER','Your Visit is Comming soon','DISMISSED');
INSERT INTO `theme-park-db`.`employees`(customer_id,title,type,message,status) VALUES ('CUST058','Don''t Forget','REMINDER','Your Visit is Comming soon','READ');
INSERT INTO `theme-park-db`.`employees`(customer_id,title,type,message,status) VALUES ('CUST044','Don''t Forget','PROMO','Visit us this upcoming holiday','READ');
INSERT INTO `theme-park-db`.`employees`(customer_id,title,type,message,status) VALUES ('CUST096','Important Message','PROMO','Visit us this upcoming holiday','READ');
INSERT INTO `theme-park-db`.`employees`(customer_id,title,type,message,status) VALUES ('CUST009','Just a Reminder','REMINDER','Your Visit is Comming soon','DISMISSED');
INSERT INTO `theme-park-db`.`employees`(customer_id,title,type,message,status) VALUES ('CUST049','Just a Reminder','PROMO','Visit us this upcoming holiday','READ');
INSERT INTO `theme-park-db`.`employees`(customer_id,title,type,message,status) VALUES ('CUST099','Don''t Forget','PROMO','Visit us this upcoming holiday','DISMISSED');
INSERT INTO `theme-park-db`.`employees`(customer_id,title,type,message,status) VALUES ('CUST094','Don''t Forget','REMINDER','Your Visit is Comming soon','SENT');
INSERT INTO `theme-park-db`.`employees`(customer_id,title,type,message,status) VALUES ('CUST092','Don''t Forget','REMINDER','Your Visit is Comming soon','READ');
INSERT INTO `theme-park-db`.`employees`(customer_id,title,type,message,status) VALUES ('CUST038','Don''t Forget','PROMO','Visit us this upcoming holiday','READ');
INSERT INTO `theme-park-db`.`employees`(customer_id,title,type,message,status) VALUES ('CUST016','Just a Reminder','REMINDER','Your Visit is Comming soon','READ');
INSERT INTO `theme-park-db`.`employees`(customer_id,title,type,message,status) VALUES ('CUST081','Don''t Forget','REMINDER','Your Visit is Comming soon','DISMISSED');
INSERT INTO `theme-park-db`.`employees`(customer_id,title,type,message,status) VALUES ('CUST024','Important Message','PROMO','Visit us this upcoming holiday','READ');
INSERT INTO `theme-park-db`.`employees`(customer_id,title,type,message,status) VALUES ('CUST025','Important Message','REMINDER','Your Visit is Comming soon','DISMISSED');
INSERT INTO `theme-park-db`.`employees`(customer_id,title,type,message,status) VALUES ('CUST016','Don''t Forget','PROMO','Visit us this upcoming holiday','DISMISSED');
INSERT INTO `theme-park-db`.`employees`(customer_id,title,type,message,status) VALUES ('CUST009','Don''t Forget','PROMO','Visit us this upcoming holiday','READ');
INSERT INTO `theme-park-db`.`employees`(customer_id,title,type,message,status) VALUES ('CUST042','Don''t Forget','REMINDER','Your Visit is Comming soon','SENT');
INSERT INTO `theme-park-db`.`employees`(customer_id,title,type,message,status) VALUES ('CUST096','Just a Reminder','PROMO','Visit us this upcoming holiday','DISMISSED');
INSERT INTO `theme-park-db`.`employees`(customer_id,title,type,message,status) VALUES ('CUST085','Don''t Forget','PROMO','Visit us this upcoming holiday','READ');
INSERT INTO `theme-park-db`.`employees`(customer_id,title,type,message,status) VALUES ('CUST005','Just a Reminder','PROMO','Visit us this upcoming holiday','DISMISSED');
INSERT INTO `theme-park-db`.`employees`(customer_id,title,type,message,status) VALUES ('CUST083','Don''t Forget','PROMO','Visit us this upcoming holiday','DISMISSED');
INSERT INTO `theme-park-db`.`employees`(customer_id,title,type,message,status) VALUES ('CUST066','Just a Reminder','REMINDER','Your Visit is Comming soon','DISMISSED');
INSERT INTO `theme-park-db`.`employees`(customer_id,title,type,message,status) VALUES ('CUST053','Don''t Forget','REMINDER','Your Visit is Comming soon','READ');
INSERT INTO `theme-park-db`.`employees`(customer_id,title,type,message,status) VALUES ('CUST005','Just a Reminder','PROMO','Visit us this upcoming holiday','SENT');
INSERT INTO `theme-park-db`.`employees`(customer_id,title,type,message,status) VALUES ('CUST068','Don''t Forget','PROMO','Visit us this upcoming holiday','DISMISSED');
INSERT INTO `theme-park-db`.`employees`(customer_id,title,type,message,status) VALUES ('CUST062','Don''t Forget','PROMO','Visit us this upcoming holiday','DISMISSED');
INSERT INTO `theme-park-db`.`employees`(customer_id,title,type,message,status) VALUES ('CUST097','Important Message','REMINDER','Your Visit is Comming soon','SENT');
INSERT INTO `theme-park-db`.`employees`(customer_id,title,type,message,status) VALUES ('CUST055','Just a Reminder','REMINDER','Your Visit is Comming soon','DISMISSED');
INSERT INTO `theme-park-db`.`employees`(customer_id,title,type,message,status) VALUES ('CUST008','Don''t Forget','REMINDER','Your Visit is Comming soon','READ');
INSERT INTO `theme-park-db`.`employees`(customer_id,title,type,message,status) VALUES ('CUST026','Important Message','REMINDER','Your Visit is Comming soon','DISMISSED');
INSERT INTO `theme-park-db`.`employees`(customer_id,title,type,message,status) VALUES ('CUST071','Important Message','REMINDER','Your Visit is Comming soon','READ');
INSERT INTO `theme-park-db`.`employees`(customer_id,title,type,message,status) VALUES ('CUST056','Important Message','PROMO','Visit us this upcoming holiday','SENT');
INSERT INTO `theme-park-db`.`employees`(customer_id,title,type,message,status) VALUES ('CUST096','Important Message','REMINDER','Your Visit is Comming soon','SENT');
INSERT INTO `theme-park-db`.`employees`(customer_id,title,type,message,status) VALUES ('CUST037','Just a Reminder','PROMO','Visit us this upcoming holiday','DISMISSED');
INSERT INTO `theme-park-db`.`employees`(customer_id,title,type,message,status) VALUES ('CUST089','Important Message','PROMO','Visit us this upcoming holiday','SENT');
INSERT INTO `theme-park-db`.`employees`(customer_id,title,type,message,status) VALUES ('CUST050','Important Message','REMINDER','Your Visit is Comming soon','DISMISSED');
INSERT INTO `theme-park-db`.`employees`(customer_id,title,type,message,status) VALUES ('CUST071','Important Message','REMINDER','Your Visit is Comming soon','READ');
INSERT INTO `theme-park-db`.`employees`(customer_id,title,type,message,status) VALUES ('CUST042','Don''t Forget','PROMO','Visit us this upcoming holiday','SENT');
INSERT INTO `theme-park-db`.`employees`(customer_id,title,type,message,status) VALUES ('CUST023','Just a Reminder','REMINDER','Your Visit is Comming soon','SENT');
INSERT INTO `theme-park-db`.`employees`(customer_id,title,type,message,status) VALUES ('CUST015','Don''t Forget','REMINDER','Your Visit is Comming soon','SENT');
