"""converted employee relationship to optional in guest services.

Revision ID: 0ab59e18949a
Revises: a7f6cf340831
Create Date: 2024-10-24 08:37:14.111982

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0ab59e18949a'
down_revision: Union[str, None] = 'a7f6cf340831'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('guestservices_ibfk_2', 'guestservices', type_='foreignkey')
    op.create_foreign_key('guestservices_ibfk_2', 'guestservices', 'employees', ['employee_id'], ['employee_id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
