"""converted ids from int to str.

Revision ID: 1d7a694477cd
Revises: 629f216765ac
Create Date: 2024-10-24 20:49:35.484116

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '1d7a694477cd'
down_revision: Union[str, None] = '629f216765ac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('sales_order_details_ibfk_1', 'sales_order_details', type_='foreignkey')
    op.alter_column('sales_order_details', 'transaction_id',
               existing_type=mysql.INTEGER(),
               type_=mysql.VARCHAR(length=12),
               existing_comment='Foreign key referencing the sales order',
               existing_nullable=False)
    op.alter_column('sales_orders', 'transaction_id',
               existing_type=mysql.INTEGER(),
               type_=mysql.VARCHAR(length=12),
               existing_comment='Unique identifier for each sales order',
               existing_nullable=False)
    op.create_foreign_key('sales_order_details_ibfk_1', 'sales_order_details', 'sales_orders', ['transaction_id'], ['transaction_id'], ondelete='CASCADE')
    
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sales_order_details', 'transaction_id',
               existing_type=mysql.VARCHAR(length=12),
               type_=mysql.INTEGER(),
               existing_comment='Foreign key referencing the sales order',
               existing_nullable=False)
    op.alter_column('sales_orders', 'transaction_id',
               existing_type=mysql.VARCHAR(length=12),
               type_=mysql.INTEGER(),
               existing_comment='Unique identifier for each sales order',
               existing_nullable=False)
    # ### end Alembic commands ###
