"""Change length of jti token

Revision ID: 25b0f9fd853d
Revises: fe61c075d3ad
Create Date: 2024-10-26 23:07:50.573196

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '25b0f9fd853d'
down_revision: Union[str, None] = 'fe61c075d3ad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('token_blocklist', 'jti',
               existing_type=mysql.VARCHAR(length=255),
               type_=sqlmodel.sql.sqltypes.AutoString(length=400),
               existing_nullable=False)
    op.drop_index('ix_token_blocklist_jti', table_name='token_blocklist')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_token_blocklist_jti', 'token_blocklist', ['jti'], unique=False)
    op.alter_column('token_blocklist', 'jti',
               existing_type=sqlmodel.sql.sqltypes.AutoString(length=400),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=False)
    # ### end Alembic commands ###
