"""added item id and updated relationships with po item id in child tables after changing dtype.

Revision ID: 685fb2948bde
Revises: 46929d2bade4
Create Date: 2024-10-23 08:47:58.004017

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '685fb2948bde'
down_revision: Union[str, None] = '46929d2bade4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('purchaseorderitems', 'id',
               existing_type=mysql.INTEGER(),
               type_=mysql.VARCHAR(length=12),
               comment='Primary key for po items.',
               existing_comment='Unique identifier for items needed to be purchased for Work Orders.',
               existing_nullable=False)
    op.alter_column('workorderitems', 'po_item_id',
               existing_type=mysql.INTEGER(),
               type_=mysql.VARCHAR(length=12),
               existing_comment='Foreign key to the Purchase Order table.',
               existing_nullable=False)
    op.create_foreign_key(None, 'workorderitems', 'purchaseorderitems', ['po_item_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'workorderitems', type_='foreignkey')
    op.alter_column('workorderitems', 'po_item_id',
               existing_type=mysql.VARCHAR(length=12),
               type_=mysql.INTEGER(),
               existing_comment='Foreign key to the Purchase Order table.',
               existing_nullable=False)
    op.alter_column('purchaseorderitems', 'id',
               existing_type=mysql.VARCHAR(length=12),
               type_=mysql.INTEGER(),
               comment='Unique identifier for items needed to be purchased for Work Orders.',
               existing_comment='Primary key for po items.',
               existing_nullable=False)
    # ### end Alembic commands ###
