"""changed invoice id to str and updated child relationships.

Revision ID: 8400c6c4cc77
Revises: d97a7a6fb872
Create Date: 2024-10-26 08:00:54.991883

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '8400c6c4cc77'
down_revision: Union[str, None] = 'd97a7a6fb872'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('vendor_payments_ibfk_2', 'vendor_payments', type_='foreignkey')
    op.drop_constraint('workorder_ibfk_3', 'workorder', type_='foreignkey')

    op.alter_column('invoice', 'invoice_id',
               existing_type=mysql.INTEGER(),
               type_=mysql.VARCHAR(length=12),
               existing_comment='Unique identifier for each invoice (primary key)',
               existing_nullable=False)
    op.alter_column('vendor_payments', 'invoice_id',
               existing_type=mysql.INTEGER(),
               type_=mysql.VARCHAR(length=12),
               existing_comment='Foreign key linking to the associated invoice',
               existing_nullable=False)
    op.alter_column('workorder', 'invoice_id',
               existing_type=mysql.INTEGER(),
               type_=mysql.VARCHAR(length=12),
               existing_comment='Foreign key to an invoice related to the work order.',
               existing_nullable=True)
    
    op.create_foreign_key('vendor_payments_ibfk_2', 'vendor_payments', 'invoice', ['invoice_id'], ['invoice_id'])
    op.create_foreign_key('workorder_ibfk_3', 'workorder', 'invoice', ['invoice_id'], ['invoice_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('workorder', 'invoice_id',
               existing_type=mysql.VARCHAR(length=12),
               type_=mysql.INTEGER(),
               existing_comment='Foreign key to an invoice related to the work order.',
               existing_nullable=True)
    op.alter_column('vendor_payments', 'invoice_id',
               existing_type=mysql.VARCHAR(length=12),
               type_=mysql.INTEGER(),
               existing_comment='Foreign key linking to the associated invoice',
               existing_nullable=False)
    op.alter_column('invoice', 'invoice_id',
               existing_type=mysql.VARCHAR(length=12),
               type_=mysql.INTEGER(),
               existing_comment='Unique identifier for each invoice (primary key)',
               existing_nullable=False)
    # ### end Alembic commands ###
