"""add department id foreign key to employees table.

Revision ID: 963e9c267805
Revises: 9759d001386a
Create Date: 2024-11-10 10:05:24.059826

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '963e9c267805'
down_revision: Union[str, None] = '9759d001386a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_brokenrides_Maintenance_Month', table_name='brokenrides')
    op.drop_table('brokenrides')
    op.drop_table('monthlyweeklycustomercounts')
    op.drop_index('ix_frequentrides_month', table_name='frequentrides')
    op.drop_table('frequentrides')

    op.add_column('employees', sa.Column('department_id', mysql.INTEGER(), nullable=True, comment='Department employee works in'))
    op.create_foreign_key('employees_ibfk_1', 'employees', 'departments', ['department_id'], ['department_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('employees_ibfk_1', 'employees', type_='foreignkey')
    op.drop_column('employees', 'department_id')
    op.create_table('frequentrides',
    sa.Column('month', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('num_rides', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('month'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_frequentrides_month', 'frequentrides', ['month'], unique=False)
    op.create_table('monthlyweeklycustomercounts',
    sa.Column('Month', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('Week', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('Num_Customers', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('Month'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('brokenrides',
    sa.Column('Maintenance_Month', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('Num_Rides_Maintained', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('avg_rides_needing_maint', mysql.FLOAT(), nullable=False),
    sa.PrimaryKeyConstraint('Maintenance_Month'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_brokenrides_Maintenance_Month', 'brokenrides', ['Maintenance_Month'], unique=False)
    # ### end Alembic commands ###
