"""changed max length to 12 for order id.

Revision ID: 98481e3ffbb9
Revises: 534ad65d83ab
Create Date: 2024-10-23 11:08:22.160210

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '98481e3ffbb9'
down_revision: Union[str, None] = '534ad65d83ab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('orderdetails', 'order_id',
               existing_type=mysql.VARCHAR(length=10),
               type_=mysql.VARCHAR(length=12),
               existing_comment='ID of the related purchase order',
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('orderdetails', 'order_id',
               existing_type=mysql.VARCHAR(length=12),
               type_=mysql.VARCHAR(length=10),
               existing_comment='ID of the related purchase order',
               existing_nullable=False)
    # ### end Alembic commands ###
