"""changed ids to str and added autogenerate logic.

Revision ID: a04bd5f20de5
Revises: fda51a47386e
Create Date: 2024-10-26 12:38:17.656087

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'a04bd5f20de5'
down_revision: Union[str, None] = 'fda51a47386e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('workorderitems_ibfk_1', 'workorderitems', type_='foreignkey')
    op.alter_column('workorder', 'woid',
               existing_type=mysql.INTEGER(),
               type_=mysql.VARCHAR(length=12),
               existing_comment='The unique identifier for the work order.',
               existing_nullable=False)
    op.alter_column('workorder', 'maintenance_date',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DATE(),
               existing_comment='The date when maintenance is scheduled or completed.',
               existing_nullable=False)
    op.alter_column('workorderitems', 'id',
               existing_type=mysql.INTEGER(),
               type_=mysql.VARCHAR(length=12),
               existing_comment='Unique identifier for items needed to be purchased for Work Orders.',
               existing_nullable=False)
    op.alter_column('workorderitems', 'woid',
               existing_type=mysql.INTEGER(),
               type_=mysql.VARCHAR(length=12),
               existing_comment='Foreign key to the Work Orders table',
               existing_nullable=False)
    op.create_foreign_key('workorderitems_ibfk_1', 'workorderitems', 'workorder', ['woid'], ['woid'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('workorderitems', 'woid',
               existing_type=mysql.VARCHAR(length=12),
               type_=mysql.INTEGER(),
               existing_comment='Foreign key to the Work Orders table',
               existing_nullable=False)
    op.alter_column('workorderitems', 'id',
               existing_type=mysql.VARCHAR(length=12),
               type_=mysql.INTEGER(),
               existing_comment='Unique identifier for items needed to be purchased for Work Orders.',
               existing_nullable=False)
    op.alter_column('workorder', 'maintenance_date',
               existing_type=sa.DATE(),
               type_=mysql.TIMESTAMP(),
               existing_comment='The date when maintenance is scheduled or completed.',
               existing_nullable=False)
    op.alter_column('workorder', 'woid',
               existing_type=mysql.VARCHAR(length=12),
               type_=mysql.INTEGER(),
               existing_comment='The unique identifier for the work order.',
               existing_nullable=False)
    # ### end Alembic commands ###
