"""changed length of employee id from 7 to 8.

Revision ID: a2e9e16127a2
Revises: cddbe427360d
Create Date: 2024-10-26 14:47:00.690974

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'a2e9e16127a2'
down_revision: Union[str, None] = 'cddbe427360d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('employee_auth_ibfk_1', 'employee_auth', type_='foreignkey')
    op.alter_column('employee_auth', 'employee_id',
               existing_type=mysql.VARCHAR(length=7),
               type_=mysql.VARCHAR(length=8),
               existing_comment='Foreign key to employees table, may be optional',
               existing_nullable=True)
    op.create_foreign_key('employee_auth_ibfk_1', 'employee_auth', 'employees', ['employee_id'], ['employee_id'], ondelete="SET NULL")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('employee_auth', 'employee_id',
               existing_type=mysql.VARCHAR(length=8),
               type_=mysql.VARCHAR(length=7),
               existing_comment='Foreign key to employees table, may be optional',
               existing_nullable=True)
    # ### end Alembic commands ###
