"""added foreign key in sales order to sales order details.

Revision ID: a6dc30d18933
Revises: ca5545adc9c2
Create Date: 2024-10-24 21:15:34.978719

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'a6dc30d18933'
down_revision: Union[str, None] = 'ca5545adc9c2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('sales_orders_ibfk_2', 'sales_orders', type_='foreignkey')
    op.drop_constraint('sales_order_details_ibfk_1', 'sales_order_details', type_='foreignkey')
    op.alter_column('sales_order_details', 'detail_id',
            existing_type=mysql.INTEGER(),
            type_=mysql.VARCHAR(length=12),
            existing_comment='Unique identifier for each sales order detail',
            existing_nullable=False)
    op.drop_index('idx_transaction_id', table_name='sales_order_details')
    op.drop_column('sales_order_details', 'transaction_id')
    op.add_column('sales_orders', sa.Column('detail_id', mysql.VARCHAR(length=12), nullable=False, comment='Foreign key referencing the sales order'))
    op.create_foreign_key('sales_orders_ibfk_2', 'sales_orders', 'sales_order_details', ['detail_id'], ['detail_id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'sales_orders', type_='foreignkey')
    op.drop_column('sales_orders', 'detail_id')
    op.add_column('sales_order_details', sa.Column('transaction_id', mysql.VARCHAR(length=12), nullable=False, comment='Foreign key referencing the sales order'))
    op.create_foreign_key('sales_order_details_ibfk_1', 'sales_order_details', 'sales_orders', ['transaction_id'], ['transaction_id'], ondelete='CASCADE')
    op.create_index('idx_transaction_id', 'sales_order_details', ['transaction_id'], unique=False)
    # ### end Alembic commands ###
