"""drop tables created for views.

Revision ID: b0feffcfea0f
Revises: c07837137b85
Create Date: 2024-11-03 18:04:41.445715

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'b0feffcfea0f'
down_revision: Union[str, None] = 'c07837137b85'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('monthlyweeklycustomercounts')
    op.drop_index('ix_brokenrides_Maintenance_Month', table_name='brokenrides')
    op.drop_table('brokenrides')
    op.drop_index('ix_frequentrides_month', table_name='frequentrides')
    op.drop_table('frequentrides')
    op.drop_index('idx_department_role_id', table_name='deparmentroles')
    op.drop_table('deparmentroles')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('deparmentroles',
    sa.Column('department_role_id', mysql.INTEGER(), autoincrement=True, nullable=False, comment='Unique ID for each department role'),
    sa.Column('department_id', mysql.INTEGER(), autoincrement=False, nullable=False, comment='Department ID this role belongs to'),
    sa.Column('role_description', mysql.VARCHAR(length=200), nullable=False, comment='Description of the department role'),
    sa.ForeignKeyConstraint(['department_id'], ['departments.department_id'], name='deparmentroles_ibfk_1'),
    sa.PrimaryKeyConstraint('department_role_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('idx_department_role_id', 'deparmentroles', ['department_role_id'], unique=False)
    op.create_table('frequentrides',
    sa.Column('month', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('num_rides', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('month'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_frequentrides_month', 'frequentrides', ['month'], unique=False)
    op.create_table('brokenrides',
    sa.Column('Maintenance_Month', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('Num_Rides_Maintained', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('avg_rides_needing_maint', mysql.FLOAT(), nullable=False),
    sa.PrimaryKeyConstraint('Maintenance_Month'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_brokenrides_Maintenance_Month', 'brokenrides', ['Maintenance_Month'], unique=False)
    op.create_table('monthlyweeklycustomercounts',
    sa.Column('Month', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('Week', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('Num_Customers', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('Month'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
