"""remove employee first/last name and username from emp_auth

Revision ID: ba0b2baa7e65
Revises: 5b7d90318a7b
Create Date: 2024-11-10 11:26:13.990709

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'ba0b2baa7e65'
down_revision: Union[str, None] = '5b7d90318a7b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('employee_auth', 'last_name')
    op.drop_column('employee_auth', 'first_name')
    op.drop_column('employee_auth', 'username')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employee_auth', sa.Column('username', mysql.VARCHAR(length=255), nullable=False))
    op.add_column('employee_auth', sa.Column('first_name', mysql.VARCHAR(length=255), nullable=False))
    op.add_column('employee_auth', sa.Column('last_name', mysql.VARCHAR(length=255), nullable=False))
    # ### end Alembic commands ###
