"""changed order date to date from datetime.

Revision ID: ca5545adc9c2
Revises: 1d7a694477cd
Create Date: 2024-10-24 21:05:27.580180

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'ca5545adc9c2'
down_revision: Union[str, None] = '1d7a694477cd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sales_orders', 'order_date',
               existing_type=mysql.DATETIME(),
               type_=sa.DATE(),
               existing_comment='Order timestamp including both date and time',
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sales_orders', 'order_date',
               existing_type=sa.DATE(),
               type_=mysql.DATETIME(),
               existing_comment='Order timestamp including both date and time',
               existing_nullable=False)
    # ### end Alembic commands ###
