"""added password_on_create attr.

Revision ID: cddbe427360d
Revises: a04bd5f20de5
Create Date: 2024-10-26 14:29:37.544531

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel



# revision identifiers, used by Alembic.
revision: str = 'cddbe427360d'
down_revision: Union[str, None] = 'a04bd5f20de5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employee_auth', sa.Column('password_on_create', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('employee_auth', 'password_on_create')
    # ### end Alembic commands ###
