"""added logic to autogenerate id for shops model.

Revision ID: d97a7a6fb872
Revises: c91663711da6
Create Date: 2024-10-25 18:40:32.448831

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'd97a7a6fb872'
down_revision: Union[str, None] = 'c91663711da6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('shops_ibfk_1', 'shops', type_='foreignkey')
    op.alter_column('shops', 'shop_id',
               existing_type=mysql.INTEGER(),
               type_=mysql.VARCHAR(length=12),
               existing_comment='Unique identifier for each shop in the park',
               existing_nullable=False)
    op.create_foreign_key('shops_ibfk_1', 'shops', 'sections', ['park_section_id'], ['section_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('shops', 'shop_id',
               existing_type=mysql.VARCHAR(length=12),
               type_=mysql.INTEGER(),
               existing_comment='Unique identifier for each shop in the park',
               existing_nullable=False)
    # ### end Alembic commands ###
