"""changed ids to str and added autogenerate logic.

Revision ID: fda51a47386e
Revises: d5c3fe172407
Create Date: 2024-10-26 11:33:39.015344

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'fda51a47386e'
down_revision: Union[str, None] = 'd5c3fe172407'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('visit_tickets_ibfk_1', 'visit_tickets', type_='foreignkey')
    op.add_column('visit_tickets', sa.Column('visit_ticket_id', mysql.VARCHAR(length=12), nullable=False, comment='The unique identifier for the visit'))
    op.alter_column('visit_tickets', 'visit_id',
               existing_type=mysql.INTEGER(),
               type_=mysql.VARCHAR(length=12),
               comment='Foreign key for the visit',
               existing_comment='The unique identifier for the visit',
               existing_nullable=False)
    op.alter_column('visits', 'visit_id',
               existing_type=mysql.INTEGER(),
               type_=mysql.VARCHAR(length=12),
               existing_comment='The unique identifier for the visit',
               existing_nullable=False)
    op.create_foreign_key('visit_tickets_ibfk_1', 'visit_tickets', 'visits', ['visit_id'], ['visit_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('visits', 'visit_id',
               existing_type=mysql.VARCHAR(length=12),
               type_=mysql.INTEGER(),
               existing_comment='The unique identifier for the visit',
               existing_nullable=False)
    op.alter_column('visit_tickets', 'visit_id',
               existing_type=mysql.VARCHAR(length=12),
               type_=mysql.INTEGER(),
               comment='The unique identifier for the visit',
               existing_comment='Foreign key for the visit',
               existing_nullable=False)
    op.drop_column('visit_tickets', 'visit_ticket_id')
    # ### end Alembic commands ###
